language: java
jdk:
- oraclejdk8
script: ant build-language-packs
deploy:
  provider: releases
  api_key:
    secure: ADofUQPGKpl5hlJgxFCQnSqMtlrm9uCnEhgxj73HaB7SCUsLgf52UAwQ53IbI1uBePCH91yiqoAIeb6Gs7eecOc76OHP+YQAXp5dvNYvaaemxKQE98qdYNMm90nGBTneBcU0J6YSSmAO2DLxGnsPaEE+PoEQh/damICyOaqsFsk=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    branch: release
    repo: webdetails/pentahoLanguagePacks
